# Generated by Django 4.1.4 on 2022-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
