# Generated by Django 4.1.4 on 2022-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
